kind: pipeline
type: docker
name: default

steps:

- name: build-image
  image: plugins/docker
  settings:
    repo: localhost:5001/example/hello-go
    insecure: true
  volumes:
    - name: docker-sock
      path: /var/run/docker.sock

volumes:
- name: docker-sock
  host:
   path: /var/run/docker.sock
    
     